apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
     name: app01
     namespace: argocd
spec:
     project: default
     source:
       repoURL: https://github.com/abhi1-rithu2/argoCD-apps-cnfgrtn.git
       targetRevision: HEAD
       path: dev
     destination:
       server: https://kube-dns.default.svc
       namespace: app
       
     syncPolicy:
       syncOptions:
       - CreateNamespace=true
       automated:
         selfHeal: true
         prune: true
