apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
   selector:
     matchLables:
       app: app01
   replicas: 1
   template:
     metadata:
       labels:
         app: app01
     spec:
      containers:
      - name: app01
        image: rithu1320/app01
        ports:
         containerPort: 8080
