apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: argo
        url: https://vc-clq7gsqd0jevc3usitpk.apps.aws-mumbai-eks.klusternetes.com
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/abhi1-rithu2/argoCD-apps-cnfgrtn.git
        targetRevision: HEAD
        path: dev/{{cluster}}
      destination:
        server: '{{url}}'   

